# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
minecraft_versions=1.18,1.18.1,1.18.2

quilt_build_number = 23

fabricloader_version = 0.14.5
min_fabricloader_version = 0.12.6

# Mod Properties
mod_name = Chicken Nerf
mod_description = Prevents random chicken egg laying. Instead, breeding chickens produces eggs.
mod_version = 1.0.13
maven_group = net.sssubtlety
author = supersaiyansubtlety

# Dependencies
fabric_version = 0.51.1+1.18.2
min_fabric_version = 0.43.1+1.18

cloth_config_version = 6.2.62
min_cloth_config_version = 6.0.42

modmenu_version = 3.2.2
min_modmenu_version = 3.0.0

crowdin_translate_version = 1.4+1.18.2
mixin_extras_version = 0.0.10

# Mod integration
better_animals_plus_version = 1.18.2-11.0.5
architectury_version = 4.4.68

# Dev only
lazy_dfu_version = 0.1.2
winwonders_version = 0.1.2-+
dashloader_version = 2.1-dev4

# Publishing
modrinth_id = KoP5DUTS
curseforge_id = 396238

#Other
mod_gradle_scripts_ref = 1.1.5